### ISSUE TITLE
[Question] aptX Adaptive support

### ISSUE THREAD

**Issue by anonymix007** [AOSPA/android_device_asus_davinci#1]
This seems to be a repo for Asus Zenfone 9, right? It's not on the website, so I guess it's not fully ready yet?
Anyway, does it support aptX Adaptive (r2.1/2.2) and a2dp hardware offload?

**Comment by sourajitk** [comment]
> This seems to be a repo for Asus Zenfone 9, right? It's not on the website, so I guess it's not fully ready yet? Anyway, does it support aptX Adaptive (r2.1/2.2) and a2dp hardware offload?

I won't be able to reply with certainty here since I don't really own any gear that takes advantage of the new codec, but, The Verge tested aptX lossless and adaptive out on the Zenfone 9, so I guess it does support it.

https://www.theverge.com/2022/9/26/23372428/aptx-lossless-hands-on-nuratrue-pro-hd-cd-quality-audio-listening-test

**Comment by anonymix007** [comment]
Are you running a custom build of PA on a Zenfone 9? If so, can you show me which A2DP codecs are supported? Screenshot from developer settings will do. 
Given that persist.vendor.qcom.bluetooth.aptxadaptiver2_2_support=true is present, I would assume that aptX Lossless would work iff aptX Adaptive is present in codec selection menu.

**Comment by sourajitk** [comment]
> Are you running a custom build of PA on a Zenfone 9? If so, can you show me which A2DP codecs are supported? Screenshot from developer settings will do. Given that persist.vendor.qcom.bluetooth.aptxadaptiver2_2_support=true is present, I would assume that aptX Lossless would work iff aptX Adaptive is present in codec selection menu.

![img](https://user-images.githubusercontent.com/45220673/215370721-962d51d5-ef5c-4e8d-bcfb-989956ac6eb3.jpg)
Does appear to be visible

**Comment by anonymix007** [comment]
Cool, LC3 seems to be present as well.

**Comment by sourajitk** [comment]
> Cool, LC3 seems to be present as well.

If you have the right gear and are willing to test out a build, contact me at t.me/CompassNeedle

**Comment by anonymix007** [comment]
Are there any build instructions or `./rom-build.sh davinci` is enough?
UPD: nope, it's not enough.
